{% set name = "bottle" %}
{% set version = "0.12.23" %}
{% set sha256 = "f38c26395736ae4653cbeb94087d3bd1d2e1ad0c29b1d3e5384f5db20b63bc98" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/bottlepy/bottle/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - python >=3.6

test:
  imports:
    - bottle

about:
  home: http://bottlepy.org
  license: MIT
  license_file: LICENSE
  summary: Bottle is a fast, simple and lightweight WSGI micro web-framework for Python.

  description: |
    Bottle is a fast, simple and lightweight WSGI micro web-framework for Python. 
    It is distributed as a single file module and has no dependencies other than the Python Standard Library.
  doc_url: http://bottlepy.org/docs/0.12/
  dev_url: https://github.com/bottlepy/bottle

extra:
  recipe-maintainers:
    - hajapy
    - jmeppley
