{% set name = "bottle" %}
{% set version = "0.12.14" %}
{% set sha256 = "3d37cb8ebc6ab03986543280774c8b0aa028616123b9d4e2615b242fc8a291f9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/bottlepy/bottle/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - bottle

about:
  home: http://bottlepy.org
  license: MIT
  license_file: LICENSE
  summary: 'Bottle is a fast, simple and lightweight WSGI micro web-framework for Python.'

  description: |
    Bottle is a fast, simple and lightweight WSGI micro web-framework for Python. 
    It is distributed as a single file module and has no dependencies other than the Python Standard Library.
  doc_url: http://bottlepy.org/docs/0.12/
  dev_url: https://github.com/bottlepy/bottle

extra:
  recipe-maintainers:
    - hajapy
    - jmeppley
