{% set name = "bottle" %}
{% set version = "0.13.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 787e78327e12b227938de02248333d788cfe45987edca735f8f88e03472c3f47

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation
  entry_points:
    - bottle = bottle:main

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python

{% set deselect_tests = "" %}
# E - ['C:\\foo\\bar\\baz\\']
# E + ['/foo/bar/baz/']
{% set deselect_tests = " --deselect=test/test_config.py::TestINIConfigLoader::test_load_config" %}  # [win]
{% set deselect_tests = deselect_tests + " --deselect=test/test_resources.py::TestResourceManager::test_path_normalize" %}  # [win]
{% set deselect_tests = deselect_tests + " --deselect=test/test_resources.py::TestResourceManager::test_path_order" %}  # [win]
{% set deselect_tests = deselect_tests + " --deselect=test/test_resources.py::TestResourceManager::test_path_unique" %}  # [win]
{% set deselect_tests = deselect_tests + " --deselect=test/test_resources.py::TestResourceManager::test_root_path" %}  # [win]
{% set deselect_tests = deselect_tests + " --deselect=test/test_sendfile.py::TestSendFile::test_file_not_readable" %}  # [win]
{% set deselect_tests = deselect_tests + " --deselect=test/test_sendfile.py::TestSendFile::test_mime_gzip" %}  # [win]

test:
  source_files:
    - test
  imports:
    - bottle
  commands:
    - pip check
    - bottle --help
    - pytest -v test {{ deselect_tests }}
  requires:
    - pip
    - pytest

about:
  home: https://bottlepy.org
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Bottle is a fast, simple and lightweight WSGI micro web-framework for Python.
  description: |
    Bottle is a fast, simple and lightweight WSGI micro web-framework for Python.
    It is distributed as a single file module and has no dependencies other than the Python Standard Library.
  doc_url: https://bottlepy.org/docs/dev/
  dev_url: https://github.com/bottlepy/bottle

extra:
  recipe-maintainers:
    - hajapy
    - jmeppley
