{% set name = "bottle" %}
{% set version = "0.13.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/bottlepy/bottle/archive/{{ version }}.tar.gz
  sha256: 638e4fdd64ee55becd0a591ecf4aaddf27c319f5254b6bcb6959130c00c6e793

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation
  skip: True  #[py<36]

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - bottle
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://bottlepy.org
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Bottle is a fast, simple and lightweight WSGI micro web-framework for Python.

  description: |
    Bottle is a fast, simple and lightweight WSGI micro web-framework for Python.
    It is distributed as a single file module and has no dependencies other than the Python Standard Library.
  doc_url: https://bottlepy.org/docs/dev/
  dev_url: https://github.com/bottlepy/bottle

extra:
  recipe-maintainers:
    - hajapy
    - jmeppley
