# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "bZeHA5LjmxnQ2rZZDcxVH/+D31LWTxD97GyesTmAxZaJ8ix6R4Gyf2NkVXeNiJB+f+5g2B7PNX/JXahzjkVZ6sGDPxzxe4Q/duT7hXl4+ylCc8oL1DcHDevwYx5i8D/06RyQafAC7DFLTeOt06H4JhLwPnmLl4H+CWSV8Jpht4/MOFcq18cUZaDu9kQT1RfqvotdRAa6hLX12LI6ffaAFfGOP0Fda8ik4RriJtFZ7VUgP7GPsMMB9skeTteeB37ZzI51r7G20gl4xV+7MET+K/7vJIaDHyqJ6h0IZwtjEsol0xRygKVXJsdoX9cC1j8g1N+LhmjB+uPi9WBZ8MO+2UgQQgJ4BakD2CMI+UOT8m+y56uHyPpLIm/Twc1Bg+g6ao0iWgDCvINs5Re7iH5twdxsnrNnlS4j7atUPcCHeX3AwgyTIg4zdFndmVeCl1QhDO/0YlZcX8iuaIrg/4QE6t96UU/K/E+5GyiKO9D2z20x0QxInFT1GcfgzxBQm9uaO1IljWMJjHjnZahLCPgs7yt1HJUMvDHQJB0UHIOAE+cjV/8iXPkO9sFst0BgpTzmyj1T+9ZxsVFZgJqlnuPQN/mO1NKySDwaI76KMdctRSryLra8q2T8diXFv1smEx92wD7WHBOpmJ+lchCYKcCf5bFh2fed0XxiX+nGo57caIM="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
