travis:
  secure:
    BINSTAR_TOKEN: bZeHA5LjmxnQ2rZZDcxVH/+D31LWTxD97GyesTmAxZaJ8ix6R4Gyf2NkVXeNiJB+f+5g2B7PNX/JXahzjkVZ6sGDPxzxe4Q/duT7hXl4+ylCc8oL1DcHDevwYx5i8D/06RyQafAC7DFLTeOt06H4JhLwPnmLl4H+CWSV8Jpht4/MOFcq18cUZaDu9kQT1RfqvotdRAa6hLX12LI6ffaAFfGOP0Fda8ik4RriJtFZ7VUgP7GPsMMB9skeTteeB37ZzI51r7G20gl4xV+7MET+K/7vJIaDHyqJ6h0IZwtjEsol0xRygKVXJsdoX9cC1j8g1N+LhmjB+uPi9WBZ8MO+2UgQQgJ4BakD2CMI+UOT8m+y56uHyPpLIm/Twc1Bg+g6ao0iWgDCvINs5Re7iH5twdxsnrNnlS4j7atUPcCHeX3AwgyTIg4zdFndmVeCl1QhDO/0YlZcX8iuaIrg/4QE6t96UU/K/E+5GyiKO9D2z20x0QxInFT1GcfgzxBQm9uaO1IljWMJjHjnZahLCPgs7yt1HJUMvDHQJB0UHIOAE+cjV/8iXPkO9sFst0BgpTzmyj1T+9ZxsVFZgJqlnuPQN/mO1NKySDwaI76KMdctRSryLra8q2T8diXFv1smEx92wD7WHBOpmJ+lchCYKcCf5bFh2fed0XxiX+nGo57caIM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
