travis:
  secure:
    BINSTAR_TOKEN: QOd7RywXKqr2yDhUg7YExO9JhVZLjLO+IiuOh3R/AVakGmGvoLd5VYYQ6vmXSX8HXA7Wh0bwFDqqcB33Bb9xr9Di+/XqSaNbHjq43Exj0cdX24SlCa8MQ8LKLoKCGEwkvuyuigLJmS7KJ2+oCZh0LOWpNad4OkXLvKS5QvEthnJ1Ql7pRK1IwdxAMNLwwUh7ksr1o1dpm2Glp9tPTYYDq4dCXZakZs7mOS9sMck2F1KXKml6I4NLDQJKI0/4jzpxPoi+BVuWWzRXeG1Vl8g/q7+flEHEUQ69v6DmGapk6irrupXLFOExM9LXhFu9eTM+fJPlPRQ+y1KW1LygNYCo+HEUKmKnuh8JjlGssUW7Minbx3zxrYdXzUa7RgYC25wXK3IPUYsPh2ENB9WB8thdwuhchYfQ8OvE7IMsqZldKfe7YYMbWSHWPMx4cwZiQqNmI67paZp+hQ5BN7F3wntEvt+N/Y7fEhQ7Yhg3GSqIOopOuwfF3rrDWzTZjGgNfeH0h4aF8ttK02LYpmQ/BbCM6tdbciL4ScYvq+eSW82ShInydoKYgh+SQ3au5c/fyHISnL7LEBAWLf0bA+UL9jVZleAW6/2CYc/pWedfiZEqEV4Idfh3TyjH5dTHPNYZEvz4zkqFcIly8EcMkkTIrhywddy6Xv6firc0l93g80lKrJU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
